name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # Paket untuk fitur yang sudah ada
  http: ^1.2.1
  image_picker: ^1.0.7
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  mesh_gradient: ^1.3.8 
  url_launcher: ^6.2.5 
  sizer: ^3.1.3
  package_info_plus: ^9.0.0
  
  # Tambahan untuk fitur 3D
  flutter_3d_controller: ^1.3.0

  # WAJIB: Paket untuk menyimpan data (seperti pilihan bahasa)
  shared_preferences: ^2.2.2 # Versi terbaru yang stabil
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brands/apple.png
    - assets/brands/huawei.png
    - assets/brands/infinix.png
    - assets/brands/itel.png
    - assets/brands/oppo.png
    - assets/brands/realme.png
    - assets/brands/samsung.png
    - assets/brands/tecno.png
    - assets/brands/vivo.png
    - assets/brands/xiaomi.png
